# This is a basic workflow to help you get started with Actions



# Controls when the workflow will run

  # Triggers the workflow on push or pull request events but only for the main bra


  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel

  # This workflow contains a single job called "build"

    # The type of runner that the job will run on

    # Steps represent a sequence of tasks that will be executed as part of the job

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   

      # Runs a single command using he runners shell
 

      # Runs a set of commands using the runners shell
       
name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - name: Update

        uses: sudo apt-get update -y
      - name: Install dpkg
        uses: sudo apt-get install -y dpkg
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
